.\" SPDX-License-Identifier: MIT
.\" SPDX-FileCopyrightText: © 2025 Regents of The University of Michigan
.\"
.\" This file is part of pam_okta and is distributed under the terms of
.\" the MIT license.
.Dd 2026-03-19
.Dt PAM_OKTA_AUTH 8
.Os pam_okta 0.5.0-alpha.1
.Sh NAME
.Nm pam_okta
.Nd PAM module for Okta
.Sh SYNOPSIS
.Nm pam_okta.so
.Op Cm config_file= Ns Ar FILENAME
.Op Cm autopush
.Op Cm password_auth
.Op Cm try_first_pass
.Op Cm use_first_pass
.Sh DESCRIPTION
.Nm
authenticates users against the Okta authentication service.
.Sh OPTIONS
.Bl -tag -width Ds
.It Cm config_file= Ns Ar FILENAME
Specify a config file to load instead of
.Pa /etc/security/pam_okta.toml
.It Cm autopush
Automatically initiate push verification instead of prompting for a passcode.
.It Cm password_auth
Perform primary authentication against Okta using a password.
The user may still be prompted to use an additional factor if the Okta
authentication policy requires one.
.It Cm try_first_pass
Try the password (if any) supplied to a prior module in the stack before
prompting for one.
.It Cm use_first_pass
Use the password supplied to a prior module in the stack instead of prompting
for one.
Primary authentication will fail if none is available.
.El
.Sh CONFIGURATION
.Pp
The configuration file needs to be owned by root (uid: 0) with group and other permissions unset (i.e. u=rw,g=,o=).
.Ss OPTIONS
.Bl -tag -width Ds
.It Cm host
Okta tenant hostname (required)
.It Cm client_id
OAuth2 client ID (required)
.It Cm client_secret
OAuth2 client secret (required)
.It Cm debug
Boolean flag to enable increased log verbosity.
.It Cm http_proxy
URI of the proxy to use for requests.
.El
.Sh SEE ALSO
.Bl -item
.It
.Xr PAM 8
.It
.Xr pam.conf 5
.El
