# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2025 Regents of The University of Michigan
#
# This file is part of pam_okta and is distributed under the terms of
# the MIT license.

name: build
on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install rustfmt
        run: |
          sudo apt update
          sudo apt install rustfmt

      - name: Check code formatting
        run: |
          cargo fmt
          git diff
          git status --porcelain | grep -q '^ M' && exit 1 || exit 0

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install rustfmt
        run: |
          sudo apt update
          sudo apt install rust-clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install cargo libpam-dev

      - name: Build package
        run: cargo package

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          path: target/package/pam_okta-*.crate
          name: crate

  build-el:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        el_version: [8, 9]
    runs-on: ubuntu-latest
    container: ghcr.io/umich-iam/pam_okta-build:el${{ matrix.el_version }}
    steps:
      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: crate

      - name: Build RPM
        run: rpmbuild -ta pam_okta-*.crate

      - name: Upload RPM
        uses: actions/upload-artifact@v7
        with:
          name: el${{ matrix.el_version }}
          path: |
            ~/rpmbuild/RPMS/noarch/*
            ~/rpmbuild/RPMS/x86_64/*
            ~/rpmbuild/SRPMS/*

  build-alma-el:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        el_version: [10]
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.el_version }}
    steps:
      - name: Install build deps
        run: dnf install -y git gzip make pam-devel rpmdevtools rust-toolset selinux-policy-devel

      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: crate

      - name: Build RPM
        run: rpmbuild -ta pam_okta-*.crate

      - name: Upload RPM
        uses: actions/upload-artifact@v7
        with:
          name: el${{ matrix.el_version }}
          path: |
            ~/rpmbuild/RPMS/noarch/*
            ~/rpmbuild/RPMS/x86_64/*
            ~/rpmbuild/SRPMS/*

  build-deb:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install build deps
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install libpam-dev make nfpm rust-all

      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: crate

      - name: Build .deb
        run: |
          tar --strip-components=1 -xvaf pam_okta-*.crate
          make deb

      - name: Upload .deb
        uses: actions/upload-artifact@v7
        with:
          name: deb.${{ endsWith(matrix.runner, '-arm') && 'arm64' || 'amd64' }}
          path: deb/*

  release:
    if: github.ref_type == 'tag'
    needs:
      - build-el
      - build-alma-el
      - build-deb
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --verify-tag \
            --notes "$GITHUB_REF_NAME" \
            --repo "$GITHUB_REPOSITORY" \
            --draft \
            --title "$GITHUB_REF_NAME" \
            pam_okta* \
            RPMS/*/* \
            SRPMS/*
