# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2025 Regents of The University of Michigan
#
# This file is part of pam_okta and is distributed under the terms of
# the MIT license.

name: dependencies
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install cargo libpam-dev

      - name: Check for dependency updates
        run: |
          cargo update
          git status --porcelain | grep -q '^ M' && cargo build
          git diff
          git status --porcelain | grep -q '^ M' && exit 1 || exit 0
